version: '3.4'
services:
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - REDIS_URL=redis
    depends_on:
      - redis
  redis: 
    image: redis:alpine
    ports:
      - 6379:6379
    volumes: 
      - redisDB:/data/
volumes:
  redisDB: